version: "3.9"
services:
  db:
    image: mariadb:10.5.15
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_ROOT_HOST=localhost
      - MARIADB_MYSQL_LOCALHOST_USER=yes
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
      - MARIADB_AUTO_UPGRADE=yes
    volumes:
      - db:/var/lib/mysql
  php:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    volumes:
      - wordpress:/wp/wp-content/uploads
  httpd:
    build:
      context: ../
      dockerfile: docker/httpd/Dockerfile
    ports:
      - 80:80
    volumes:
      - wordpress:/wp/wp-content/uploads

volumes:
  db:
  wordpress: